#!/usr/bin/env bash
set -x
set -e
./gradlew clean test distTar
scp build/distributions/hell-1.0.tar plex@45.55.153.133:~
/opt/local/bin/ansible all -i '45.55.153.133,' -u plex -m command -a "rm -rf hell-1.0/"
/opt/local/bin/ansible all -i '45.55.153.133,' -u plex -m command -a "tar xf hell-1.0.tar"
/opt/local/bin/ansible all -i '45.55.153.133,' -u plex -m command -a "sv restart hell"
http 45.55.153.133:8080 | diff - test.tmp
